import torch
from langchain_chroma import Chroma
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document


#creating directory
CHROMA_DIR = "vector_db"
COLLECTION_NAME = "meeting_transcript" #to save meeting transcript
EMBEDDING_MODEL = "all-MiniLM-L6-v2"


def get_embeddings():
    return HuggingFaceBgeEmbeddings(
        model_name = EMBEDDING_MODEL,
        model_kwargs = {"device": "cuda" if torch.cuda.is_available() else "cpu"}
    )

def build_vector_store(transcript : str) -> Chroma:
    print("Building Vector Store")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size = 500,
        chunk_overlap = 50
    )

    chunks = splitter.split_text(transcript)

    #Wrapping in langchain document



    docs = [
    Document(page_content=chunk, metadata = ({'chunk_index': i}))
    for i, chunk in enumerate(chunks)
    ]


    embeddings = get_embeddings()
    vector_store = Chroma.from_documents(
    documents= docs,
    embedding = embeddings,
    collection_name = COLLECTION_NAME,
    persist_directory = CHROMA_DIR
    )

    return vector_store


def load_vector_store() -> Chroma:
    embeddings = get_embeddings()
    vector_store = Chroma(  #this will tell all loaction and all if we want to load
        collection_name = COLLECTION_NAME,
        embedding_function= embeddings,
        persist_directory= CHROMA_DIR
    )

    return vector_store

#Once we get loaction that we have to retreive as well for that we use retriver


def get_retriver(vector_store: Chroma, k: int = 4):
    return vector_store.as_retriever(
        search_type = 'similarity',
        search_kwargs = {"k": k}
    )





























































# what is persist directory and collection name parametr in from_document()

# 2:54 AM
# View 1 tool calls
# search_docs_by_lang_chain
# Arguments
# 2:54 AM
# View 1 tool calls
# 2:54 AM
# View 1 tool calls
# 2:54 AM
# persist_directory and collection_name are configuration parameters used when initializing Chroma vector stores in langchain-chroma (such as in Chroma.from_documents()).

# persist_directory
# The persist_directory parameter specifies the local file path where Chroma stores your vector database on disk.

# When provided, Chroma automatically saves embeddings, metadata, and document chunks to this directory so they persist across script runs and application restarts. If omitted, Chroma runs entirely in memory, and all stored data is lost when the Python process exits.

# vector_store = Chroma.from_documents(
#     documents=docs,
#     embedding=embeddings,
#     persist_directory="./chroma_langchain_db",  # Local disk path
# )
# collection_name
# The collection_name parameter defines the logical namespace or table name within the Chroma database where your documents are grouped.

# A single Chroma database instance can contain multiple isolated collections. By default, Chroma uses "langchain" as the collection name if none is specified, but setting a custom name helps organize different sets of documents within the same persist directory.

# vector_store = Chroma.from_documents(
#     documents=docs,
#     embedding=embeddings,
#     collection_name="my_custom_collection",  # Namespace within Chroma
#     persist_directory="./chroma_langchain_db",
# )
# Relevant docs:

# Chroma Integration Guide
# 2:54 AM
# what will be stored in collection_name ?

# 2:54 AM
# View 1 tool calls
# 2:54 AM
# View 1 tool calls
# 2:54 AM
# The collection_name stores your actual document chunks, their generated vector embeddings, and their associated metadata.

# In Chroma, a collection acts as a table or bucket. When you pass documents to Chroma.from_documents(), Chroma stores the following information inside that collection:

# Embeddings: The numerical vector representations generated by your embedding model for each document text.
# Documents: The original text content of your chunks.
# Metadata: Any dictionary metadata attached to your Document objects (such as source file names, page numbers, or custom tags).
# IDs: Unique identifiers assigned to each stored chunk.
# from langchain_chroma import Chroma

# # All chunks, embeddings, and metadata are stored inside "my_docs"
# vector_store = Chroma.from_documents(
#     documents=docs,
#     embedding=embeddings,
#     collection_name="my_docs",
#     persist_directory="./chroma_langchain_db",
# )
